spring:
  application:
    name: account-service
server:            
  port: 8082
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}  
  instance:
    preferIPAddress: true    
    metadataMap:      instanceId: ${}spring.application.name}:${server.port} 